### ISSUE TITLE
Active issues not pinned to top

### ISSUE THREAD

**Issue by mplutka** [CrawlerCode/redmine-time-tracking#16]
I really like the new feature to pin active issues to the top. This doesn't seem to affect the project grouping/ordering as the active issue simply moves to the top of its own project but not to the top of the whole list what would be much more confient. Right now i have to scroll down to the project containing the active issue (and i have a lot of them!).
Thanks for considering an update for this.

**Comment by CrawlerCode** [comment]
Thank you for reporting this bug.

I fixed the order of the issues and release a new version (`v1.16.1`)

**Comment by qsnewuser** [comment]
Hi, Is this functionality working only for the issues where I'm an assignee? Because for me it doesn't work on other (not mine) issues. "Pin issue of active tab to the top" feature is more important for not mine issues, because you always have to search them.
For me it works like this:
- Issue of active tab where I'm assignee -> Shows on top of the list (OK)
- Issue of active tab where I'm not an assignee -> Doesn't show up in the list at all (NOK)
Thanks in advance for paying attention to this comment!

**Comment by CrawlerCode** [comment]
Yes, currently this only works for assigned issues. I added this to my to-do list and will improve this feature in the future.
